#!/usr/bin/env bash
set -euo pipefail

ROOT=${ROOT:-$(pwd)}
cd "${ROOT}"

PYTHON=${PYTHON:-python3}
export PYTHONDONTWRITEBYTECODE=${PYTHONDONTWRITEBYTECODE:-1}

: "${DATASET_DIR:=datasets}"
: "${DATASET_NAME:=NUDT-SIRST}"
: "${DATASET_REGISTRY:=configs/datasets.yaml}"
: "${MODEL_NAME:=MSHNetOHEM}"
: "${SEED:=42}"
: "${EPOCH:=400}"
: "${THRESHOLD:=0.5}"
: "${VAL_FRACTION:=0.35}"
: "${OUTPUT_ROOT:=docs/internal/hc_protocol_generated}"
: "${EXPORTS_DIR:=${OUTPUT_ROOT}/exports/${MODEL_NAME}/seed${SEED}/${DATASET_NAME}}"
: "${STEP1_ROOT:=${OUTPUT_ROOT}/step1_baseline}"
: "${STEP1_DIR:=${STEP1_ROOT}/${DATASET_NAME}/seed_${SEED}/step1}"
: "${HCSET_DIR:=${OUTPUT_ROOT}/hcset}"
: "${PROTOCOL_DIR:=${OUTPUT_ROOT}/hc_protocol}"
: "${FORCE:=0}"
: "${RUN_EXPORT:=1}"
: "${SYNC_TO_DATASET_IMG_IDX:=0}"
: "${RUN_SOURCE_AUDIT:=1}"
: "${SOURCE_NOTE:=Generated by OHCM hard-clutter protocol ported into CGA-main.}"

if [[ "${DATASET_NAME}" != "NUDT-SIRST" ]]; then
  echo "This entry is intentionally locked to NUDT-SIRST; got DATASET_NAME=${DATASET_NAME}" >&2
  exit 2
fi

if [[ "${RUN_EXPORT}" == "1" ]]; then
  : "${CHECKPOINT:?CHECKPOINT is required when RUN_EXPORT=1}"
  if [[ "${FORCE}" == "1" || ! -f "${EXPORTS_DIR}/summary_metrics.json" ]]; then
    "${PYTHON}" -m tools.official.export_prediction_maps \
      --model_name "${MODEL_NAME}" \
      --dataset_dir "${DATASET_DIR}" \
      --train_dataset_name "${DATASET_NAME}" \
      --dataset_name "${DATASET_NAME}" \
      --split test \
      --seed "${SEED}" \
      --checkpoint "${CHECKPOINT}" \
      --threshold "${THRESHOLD}" \
      --output_dir "${EXPORTS_DIR}"
  fi
fi

if [[ "${FORCE}" == "1" || ! -f "${STEP1_DIR}/step1_fp_components.csv" ]]; then
  "${PYTHON}" -m tools.official.analyze_step1_hard_clutter \
    --dataset_dir "${DATASET_DIR}" \
    --dataset_name "${DATASET_NAME}" \
    --exports_dir "${EXPORTS_DIR}" \
    --output_dir "${STEP1_DIR}" \
    --seed "${SEED}" \
    --threshold "${THRESHOLD}"
fi

if [[ "${FORCE}" == "1" || ! -f "${HCSET_DIR}/hcset_images.csv" ]]; then
  "${PYTHON}" -m tools.official.build_step2_hcset \
    --step1_root "${STEP1_ROOT}" \
    --output_dir "${HCSET_DIR}" \
    --datasets "${DATASET_NAME}" \
    --seed "${SEED}"
fi

"${PYTHON}" -m tools.official.split_hcset_val_test \
  --hcset_dir "${HCSET_DIR}" \
  --output_dir "${PROTOCOL_DIR}" \
  --val_fraction "${VAL_FRACTION}"

if [[ "${RUN_SOURCE_AUDIT}" == "1" ]]; then
  "${PYTHON}" -m tools.official.check_cga_v2_nudt_hcval_list_source \
    --dataset_dir "${DATASET_DIR}" \
    --dataset_name "${DATASET_NAME}" \
    --candidate_hcval_list "${PROTOCOL_DIR}/hcval_${DATASET_NAME}.txt" \
    --source_note "${SOURCE_NOTE}" \
    --registry "${DATASET_REGISTRY}" \
    --output "${PROTOCOL_DIR}/hcval_source_summary.json"
fi

if [[ "${SYNC_TO_DATASET_IMG_IDX}" == "1" ]]; then
  install -D -m 0644 \
    "${PROTOCOL_DIR}/hcval_${DATASET_NAME}.txt" \
    "${DATASET_DIR}/${DATASET_NAME}/img_idx/hcval_${DATASET_NAME}.txt"
fi

printf 'HC-Val list: %s\n' "${PROTOCOL_DIR}/hcval_${DATASET_NAME}.txt"
printf 'HC-Test list: %s\n' "${PROTOCOL_DIR}/hctest_${DATASET_NAME}.txt"
